####################################################################################
## Copyright (c) 2018 - 2024 Analog Devices, Inc.
### SPDX short identifier: BSD-1-Clause
####################################################################################

PROJECT_NAME := phase_meas_de10nano

M_DEPS += ../../scripts/adi_pd.tcl
M_DEPS += ../../common/de10nano/de10nano_system_qsys.tcl
M_DEPS += ../../common/de10nano/de10nano_system_assign.tcl

LIB_DEPS += axi_sysid
LIB_DEPS += sysid_rom
LIB_DEPS += phase_meas
LIB_DEPS += phase_dps_ctrl

include ../../scripts/project-intel.mk
